---
- import_tasks: ../common/tasks/main.yaml

- name: Configuring Bridge based at vlan iface
  ansible.builtin.template:
    src: "{{ config_seed_interfaces_template }}"
    dest: /etc/network/interfaces.d/bridge.cfg
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - Restart networking

- name: Make sure that networking was restarted after initial bridge config setup
  ansible.builtin.meta: flush_handlers

- name: Create seed user
  ansible.builtin.user:
    name: "{{ seed_username }}"
    state: present
    shell: /bin/bash
    groups: sudo
    append: true

- name: Deploy SSH Public Key
  authorized_key:
    user: "{{ seed_username }}"
    state: present
    key: "{{ lookup('file', '{{ ansible_ssh_public_key_file }}') }}"

- name: Passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
