---
- name: Update packages list
  ansible.builtin.apt:
    update_cache: true

- name: Make sure interfaces.d included in common configuration
  become: true
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    line: "source /etc/network/interfaces.d/*.cfg"
    state: present
  notify:
    - Restart networking

- name: Install bridge-utils
  ansible.builtin.package:
    name: bridge-utils
    state: present

- name: Get network configuration from file
  ansible.builtin.include_vars:
    file: "{{ network_config_path }}"
    name: network_configuration
