---
- name: Create routers
  hosts: routers
  gather_facts: true
  become: true
  roles:
    - role: edge_router
    - role: squid_proxy
    - role: ntp_server
    - role: dhcp_relay
      when: dhcp_servers | length  > 0
- name: Create seed
  hosts: seed
  gather_facts: true
  become: true
  roles:
    - role: mcc_seed
    - role: docker
